using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ZeroAlloc.Validation.Generator.Shared;

namespace ZeroAlloc.Validation.Inject;

[Generator]
public sealed class InjectGenerator : IIncrementalGenerator
{
    private const string ValidateAttributeFqn = "ZeroAlloc.Validation.ValidateAttribute";

    /// <summary>Tracking name of the step the output is produced from, so tests can assert that it stays cached.</summary>
    internal const string OutputTrackingName = "ValidatorRegistrations";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validateClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValidateAttributeFqn,
                // RecordDeclarationSyntax is a sibling of ClassDeclarationSyntax under
                // TypeDeclarationSyntax, not a subtype, so matching only the latter
                // skipped every [Validate] record. The per-type validators still
                // generated, because ValidatorGenerator matches both, so the package
                // looked like it was working while AddZeroAllocValidators was never
                // emitted at all.
                predicate: static (node, _) => node is ClassDeclarationSyntax
                                                    or RecordDeclarationSyntax,
                // A model that gets no validator is left out here too: one the generated validator
                // cannot reach, ZV0025 and #216, or one whose type parameters it cannot redeclare,
                // ZV0029 and #219. Naming it would only add compiler errors in generated code. A
                // generic model is left out as a root, since nothing closed can be registered for
                // it; its closings are registered by the models composing them, issue #238.
                // Null marks it, and the step after Collect drops it.
                // The transform extracts everything the output needs into an equatable model, so
                // the output step stays cached while nothing it was read from changes, issue #209.
                // It reruns for every compilation, so the model still follows edits in other
                // files, such as to a nested model, and into referenced assemblies, issue #246.
                transform: static (ctx, _) =>
                    GeneratedValidatorReach.HasGeneratedValidator((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation)
                    && !GeneratedValidatorReach.IsGeneric((INamedTypeSymbol)ctx.TargetSymbol)
                        ? ValidatedModelInfo.From((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation)
                        : null);

        var collected = validateClasses.Collect()
            .Select(static (models, _) => ValidatedModelInfo.WithGeneratedValidator(models));
        var isInternal = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => GeneratedAccessibilityOption.IsInternal(provider));
        var combined = collected.Combine(isInternal).WithTrackingName(OutputTrackingName);
        context.RegisterSourceOutput(combined, static (ctx, pair) => Emit(ctx, pair.Left, pair.Right));
    }

    private static void Emit(SourceProductionContext ctx, EquatableArray<ValidatedModelInfo> models, bool isInternal)
    {
        if (models.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        // Documented rather than suppressed with #pragma warning disable CS1591: the
        // <auto-generated> header does not cover compiler diagnostics, and real documentation
        // also reaches the consumer's own XML documentation file.
        sb.AppendLine("/// <summary>Registers the generated validators with the dependency injection container.</summary>");
        // ZeroAllocGeneratedAccessibility=Internal (issue #193) makes this DI glue internal too,
        // regardless of whether the [Validate] models it registers are public or internal — the
        // method signature only ever exposes IServiceCollection, so there is no accessibility
        // conflict to resolve, unlike the generated validator classes themselves.
        sb.AppendLine(isInternal
            ? "internal static class ZeroAllocValidatorRegistrationExtensions"
            : "public static class ZeroAllocValidatorRegistrationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registers every generated validator in this assembly with the service collection.</summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add the validator registrations to.</param>");
        sb.AppendLine("    /// <returns>The same service collection, so calls can be chained.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocValidators(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        ValidatorRegistrationEmitter.AppendRegistrations(sb, models);
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("ZeroAlloc.Validation.ZeroAllocValidatorRegistrationExtensions.g.cs", sb.ToString());
    }
}
