using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Xunit;
using ZeroAlloc.Validation.Generator;
using ZeroAlloc.Validation.Inject;
using ZeroAlloc.Validation.Options.Generator;

namespace ZeroAlloc.Validation.Tests.Generator;

/// <summary>
/// Issue #238, phase 2: a generic <c>[Validate]</c> model gets a registration helper generic over
/// its type parameters, <c>services.AddPageValidator&lt;Customer&gt;()</c>, in a static class in
/// the model's namespace, and a <c>ValidateWithZeroAlloc&lt;…&gt;()</c> overload that inference
/// closes from the options builder. Both register the model's validator and every validator it
/// takes, closed at the call site. Every source here is compiled with the generated files, so an
/// error or warning in generated code fails the test.
/// </summary>
public class GenericRegistrationHelperTests
{
    private const string PageModels = """
        using System.Collections.Generic;
        using ZeroAlloc.Validation;
        namespace Ns;

        public class Customer { }

        [Validate]
        public class Page<TItem> where TItem : class
        {
            [NotEmpty] public string Title { get; set; } = "";
            public List<Line<TItem>> Lines { get; set; } = new();
        }

        [Validate]
        public class Line<TItem> where TItem : class
        {
            [GreaterThan(0)] public int Quantity { get; set; }
            [NotNull] public TItem? Item { get; set; }
        }
        """;

    private const string HelperHint = "Ns.ZeroAllocGenericValidatorRegistrationExtensions.g.cs";

    [Fact]
    public void GenericModel_GetsARegistrationHelperInItsNamespace()
    {
        var output = GenericModelTestHost.Run(PageModels).Compiles();

        Assert.Equal(
            """
            // <auto-generated />
            #nullable enable

            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;

            namespace Ns;

            /// <summary>Registers the generated validators of the generic models in this namespace, closed over the type arguments of each call.</summary>
            public static class ZeroAllocGenericValidatorRegistrationExtensions
            {
                /// <summary>Registers the validator of <c>Page</c> closed over the given type arguments, and every validator it takes.</summary>
                /// <typeparam name="TItem">The type argument for the <c>TItem</c> type parameter of <c>Page</c>.</typeparam>
                /// <param name="services">The service collection to add the registrations to.</param>
                /// <returns>The same service collection, so calls can be chained.</returns>
                public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddPageValidator<TItem>(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                    where TItem : class
                {
                    services.TryAddSingleton<global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Page<TItem>>, global::Ns.PageValidator<TItem>>();
                    services.TryAddEnumerable(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::ZeroAlloc.Validation.IModelValidator, global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Page<TItem>>>(static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Page<TItem>>>(sp)));
                    services.TryAddSingleton<global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Line<TItem>>, global::Ns.LineValidator<TItem>>();
                    services.TryAddEnumerable(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::ZeroAlloc.Validation.IModelValidator, global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Line<TItem>>>(static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Line<TItem>>>(sp)));
                    return services;
                }

                /// <summary>Registers the validator of <c>Line</c> closed over the given type arguments, and every validator it takes.</summary>
                /// <typeparam name="TItem">The type argument for the <c>TItem</c> type parameter of <c>Line</c>.</typeparam>
                /// <param name="services">The service collection to add the registrations to.</param>
                /// <returns>The same service collection, so calls can be chained.</returns>
                public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddLineValidator<TItem>(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                    where TItem : class
                {
                    services.TryAddSingleton<global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Line<TItem>>, global::Ns.LineValidator<TItem>>();
                    services.TryAddEnumerable(global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::ZeroAlloc.Validation.IModelValidator, global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Line<TItem>>>(static sp => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Line<TItem>>>(sp)));
                    return services;
                }
            }

            """.ReplaceLineEndings("\n"),
            output.Source(HelperHint).ReplaceLineEndings("\n"));
    }

    [Fact]
    public void RegistrationHelper_IsCalledWithTheClosingAsTypeArgument()
    {
        GenericModelTestHost.Run(PageModels + """

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services) =>
                    services.AddPageValidator<Customer>().AddLineValidator<string>();
            }
            """).Compiles();
    }

    [Fact]
    public void ModelWithoutGenericModels_GetsNoHelperFile()
    {
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace Ns;
            [Validate] public class Order { [NotEmpty] public string Id { get; set; } = ""; }
            """).Compiles();

        Assert.DoesNotContain(output.Generated, g => g.HintName.Contains("Generic", StringComparison.Ordinal));
    }

    [Fact]
    public void GenericModelsOfDifferentArity_GetOverloadedHelpers()
    {
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace Ns;
            [Validate] public class Box { [NotEmpty] public string Name { get; set; } = ""; }
            [Validate] public class Box<T> { [NotEmpty] public string Name { get; set; } = ""; }
            [Validate] public class Box<T, U> { [NotEmpty] public string Name { get; set; } = ""; }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services) =>
                    services.AddBoxValidator<int>().AddBoxValidator<int, string>();
            }
            """).Compiles();

        var helper = output.Source(HelperHint);
        Assert.Contains("AddBoxValidator<T>(", helper, StringComparison.Ordinal);
        Assert.Contains("AddBoxValidator<T, U>(", helper, StringComparison.Ordinal);
        Assert.DoesNotContain("AddBoxValidator(", helper, StringComparison.Ordinal);
    }

    [Fact]
    public void ModelInAGenericContainer_GetsAHelperNamedAfterItsValidator()
    {
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace Ns;
            public class Envelope<T> where T : struct
            {
                [Validate] public class Header { [NotEmpty] public string Name { get; set; } = ""; }
                [Validate] public class Part<U> where U : notnull { [NotEmpty] public string Name { get; set; } = ""; }
            }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services) =>
                    services.AddEnvelope_HeaderValidator<int>().AddEnvelope_PartValidator<int, string>();
            }
            """).Compiles();

        var helper = output.Source(HelperHint);
        Assert.Contains(
            "AddEnvelope_HeaderValidator<T>(\n        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)\n        where T : struct\n",
            helper.ReplaceLineEndings("\n"),
            StringComparison.Ordinal);
        Assert.Contains(
            "AddEnvelope_PartValidator<T, U>(\n        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)\n        where T : struct\n        where U : notnull\n",
            helper.ReplaceLineEndings("\n"),
            StringComparison.Ordinal);
        Assert.Contains("global::Ns.Envelope_PartValidator<T, U>>();", helper, StringComparison.Ordinal);
    }

    [Fact]
    public void SameNamedModelsInTwoNamespaces_GetAHelperClassEach()
    {
        // One class for both would declare AddBoxValidator<T> twice, CS0111.
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace A { [Validate] public class Box<T> { [NotEmpty] public string Name { get; set; } = ""; } }
            namespace B { [Validate] public class Box<T> { [NotEmpty] public string Name { get; set; } = ""; } }
            namespace @class.Models { [Validate] public class Crate<T> { [NotEmpty] public string Name { get; set; } = ""; } }
            [Validate] public class Bag<T> { [NotEmpty] public string Name { get; set; } = ""; }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
                    A.ZeroAllocGenericValidatorRegistrationExtensions.AddBoxValidator<int>(services);
                    B.ZeroAllocGenericValidatorRegistrationExtensions.AddBoxValidator<int>(services);
                    @class.Models.ZeroAllocGenericValidatorRegistrationExtensions.AddCrateValidator<int>(services);
                    services.AddBagValidator<int>();
                }
            }
            """).Compiles();

        Assert.Contains("namespace A;", output.Source("A.ZeroAllocGenericValidatorRegistrationExtensions.g.cs"), StringComparison.Ordinal);
        Assert.Contains("namespace B;", output.Source("B.ZeroAllocGenericValidatorRegistrationExtensions.g.cs"), StringComparison.Ordinal);
        Assert.Contains("namespace @class.Models;", output.Source("class.Models.ZeroAllocGenericValidatorRegistrationExtensions.g.cs"), StringComparison.Ordinal);
        Assert.DoesNotContain("\nnamespace ", output.Source("ZeroAllocGenericValidatorRegistrationExtensions.g.cs").ReplaceLineEndings("\n"), StringComparison.Ordinal);
    }

    [Fact]
    public void InternalGenericModel_GoesInTheInternalHelperClass()
    {
        // The helper's constraint names the internal Base, so a public helper would not compile.
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace Ns;
            internal class Base { }
            [Validate] public class Box<T> { [NotEmpty] public string Name { get; set; } = ""; }
            [Validate] internal class Crate<T> where T : Base { [NotEmpty] public string Name { get; set; } = ""; }
            public class Outer { [Validate] internal class Inner<T> { [NotEmpty] public string Name { get; set; } = ""; } }
            """).Compiles();

        var helper = output.Source(HelperHint).ReplaceLineEndings("\n");
        var publicClass = helper.IndexOf("public static class ZeroAllocGenericValidatorRegistrationExtensions", StringComparison.Ordinal);
        var internalClass = helper.IndexOf("internal static class InternalZeroAllocGenericValidatorRegistrationExtensions", StringComparison.Ordinal);
        Assert.True(publicClass >= 0 && internalClass > publicClass);
        Assert.Contains("AddBoxValidator<T>(", helper[..internalClass], StringComparison.Ordinal);
        Assert.Contains("AddCrateValidator<T>(", helper[internalClass..], StringComparison.Ordinal);
        Assert.Contains("AddOuter_InnerValidator<T>(", helper[internalClass..], StringComparison.Ordinal);
    }

    [Fact]
    public void TypeParameterNamedLikeAGeneratedIdentifier_GetsAnotherIdentifier()
    {
        // A method cannot declare a parameter, local or lambda parameter named like one of its
        // type parameters, CS0412.
        var output = GenericModelTestHost.Run(
            """
            using ZeroAlloc.Validation;
            namespace Ns;
            [Validate] public class Box<services, sp, builder, services2> where services : class
            {
                [NotEmpty] public string Name { get; set; } = "";
            }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
                    services.AddBoxValidator<string, int, int, int>();
                    Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions
                        .AddOptions<Box<string, int, int, int>>(services).ValidateWithZeroAlloc();
                }
            }
            """.Replace("namespace Ns;", "using ZeroAlloc.Validation.Options;\nnamespace Ns;", StringComparison.Ordinal),
            new ValidatorGenerator(), new InjectGenerator(), new OptionsValidationEmitter()).Compiles();

        var helper = output.Source(HelperHint);
        Assert.Contains("IServiceCollection services3)", helper, StringComparison.Ordinal);
        Assert.Contains("static sp2 => ", helper, StringComparison.Ordinal);
        var overload = output.Source("ZeroAlloc.Validation.ZeroAllocOptionsValidationExtensions.g.cs");
        Assert.Contains("> builder2)", overload, StringComparison.Ordinal);
        Assert.Contains("var services3 = builder2.Services;", overload, StringComparison.Ordinal);
    }

    [Fact]
    public void KeywordTypeParameter_IsEscapedInCodeAndNotInDocumentation()
    {
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace Ns;
            [Validate] public class Box<@class> { [NotEmpty] public string Name { get; set; } = ""; }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services) =>
                    services.AddBoxValidator<int>();
            }
            """).Compiles();

        var helper = output.Source(HelperHint);
        Assert.Contains("AddBoxValidator<@class>(", helper, StringComparison.Ordinal);
        Assert.Contains("<typeparam name=\"class\">", helper, StringComparison.Ordinal);
    }

    [Fact]
    public void GenericModelComposingAClosingOfAnother_RegistersItOverTheSameTypeParameters()
    {
        var output = GenericModelTestHost.Run("""
            using System.Collections.Generic;
            using ZeroAlloc.Validation;
            namespace Ns;
            [Validate] public class Address { [NotEmpty] public string City { get; set; } = ""; }
            [Validate] public class Pair<TKey, TValue> { [NotEmpty] public string Name { get; set; } = ""; }
            [Validate]
            public class Catalog<T> where T : Address
            {
                public Pair<T, string>? Pair { get; set; }
                public Pair<int, int>? Fixed { get; set; }
                public T? Home { get; set; }
            }
            """).Compiles();

        var helper = output.Source(HelperHint);
        var start = helper.IndexOf("AddCatalogValidator<T>", StringComparison.Ordinal);
        var catalog = helper[start..helper.IndexOf("return services;", start, StringComparison.Ordinal)];
        Assert.Contains("ValidatorFor<global::Ns.Catalog<T>>, global::Ns.CatalogValidator<T>>();", catalog, StringComparison.Ordinal);
        Assert.Contains("ValidatorFor<global::Ns.Pair<T, string>>, global::Ns.PairValidator<T, string>>();", catalog, StringComparison.Ordinal);
        Assert.Contains("ValidatorFor<global::Ns.Pair<int, int>>, global::Ns.PairValidator<int, int>>();", catalog, StringComparison.Ordinal);
        Assert.Contains("ValidatorFor<global::Ns.Address>, global::Ns.AddressValidator>();", catalog, StringComparison.Ordinal);
    }

    [Fact]
    public void GenericOptionsModel_GetsAnOverloadThatInferenceCloses()
    {
        var output = GenericModelTestHost.Run(
            PageModels.Replace("namespace Ns;", "using ZeroAlloc.Validation.Options;\nnamespace Ns;", StringComparison.Ordinal) + """

            [Validate] public class Settings { [NotEmpty] public string Name { get; set; } = ""; }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
                    Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions
                        .AddOptions<Page<Customer>>(services).ValidateWithZeroAlloc();
                    Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions
                        .AddOptions<Settings>(services).ValidateWithZeroAlloc();
                }
            }
            """,
            new ValidatorGenerator(), new OptionsValidationEmitter()).Compiles();

        var overloads = output.Source("ZeroAlloc.Validation.ZeroAllocOptionsValidationExtensions.g.cs").ReplaceLineEndings("\n");
        Assert.Contains(
            """
                /// <summary>Validates <c>Page</c> with its generated validator whenever the options instance is resolved.</summary>
                /// <typeparam name="TItem">The type argument for the <c>TItem</c> type parameter of <c>Page</c>.</typeparam>
                /// <param name="builder">The options builder to attach validation to.</param>
                /// <returns>The same options builder, so calls can be chained.</returns>
                public static global::Microsoft.Extensions.Options.OptionsBuilder<global::Ns.Page<TItem>> ValidateWithZeroAlloc<TItem>(
                    this global::Microsoft.Extensions.Options.OptionsBuilder<global::Ns.Page<TItem>> builder)
                    where TItem : class
                {
                    var services = builder.Services;
                    services.TryAddSingleton<global::ZeroAlloc.Validation.ValidatorFor<global::Ns.Page<TItem>>, global::Ns.PageValidator<TItem>>();
            """.ReplaceLineEndings("\n"),
            overloads,
            StringComparison.Ordinal);
        Assert.Contains(
            """
                    builder.Services.TryAddSingleton<global::Microsoft.Extensions.Options.IValidateOptions<global::Ns.Page<TItem>>,
                        global::ZeroAlloc.Validation.Options.ZeroAllocOptionsValidator<global::Ns.Page<TItem>>>();
                    return builder;
                }
            """.ReplaceLineEndings("\n"),
            overloads,
            StringComparison.Ordinal);
        Assert.Contains("ValidateWithZeroAlloc(\n        this global::Microsoft.Extensions.Options.OptionsBuilder<global::Ns.Settings> builder)", overloads, StringComparison.Ordinal);
    }

    [Fact]
    public void GenericOptionsModelInAGenericContainer_IsClosedByInference()
    {
        GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            using ZeroAlloc.Validation.Options;
            namespace Ns;
            public class Envelope<T> { [Validate] public class Header { [NotEmpty] public string Name { get; set; } = ""; } }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services) =>
                    Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions
                        .AddOptions<Envelope<int>.Header>(services).ValidateWithZeroAlloc();
            }
            """,
            new ValidatorGenerator(), new OptionsValidationEmitter()).Compiles();
    }

    [Fact]
    public void GenericValueTypeModel_GetsAHelperButNoOptionsOverload()
    {
        // OptionsBuilder<T> requires a reference type; the helper does not.
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace Ns;
            [Validate] public readonly record struct Slot<T>([property: NotEmpty] string Name);
            """,
            new ValidatorGenerator(), new InjectGenerator(), new OptionsValidationEmitter()).Compiles();

        Assert.Contains("AddSlotValidator<T>(", output.Source(HelperHint), StringComparison.Ordinal);
        Assert.DoesNotContain(output.Generated, g => g.HintName.Contains("Options", StringComparison.Ordinal));
    }

    [Fact]
    public void InternalGenericOptionsModel_GoesInTheInternalOverloadClass()
    {
        var output = GenericModelTestHost.Run("""
            using ZeroAlloc.Validation;
            namespace Ns;
            [Validate] internal class Box<T> { [NotEmpty] public string Name { get; set; } = ""; }
            """,
            new ValidatorGenerator(), new OptionsValidationEmitter()).Compiles();

        Assert.Contains(
            "ValidateWithZeroAlloc<T>(",
            output.Source("ZeroAlloc.Validation.InternalZeroAllocOptionsValidationExtensions.g.cs"),
            StringComparison.Ordinal);
        Assert.DoesNotContain(output.Generated, g => string.Equals(g.HintName, "ZeroAlloc.Validation.ZeroAllocOptionsValidationExtensions.g.cs", StringComparison.Ordinal));
    }

    [Fact]
    public void GenericOptionsModelWithAsynchronousRules_ReportsZV0034AtTheCall()
    {
        var output = GenericModelTestHost.Run("""
            using System.Threading;
            using System.Threading.Tasks;
            using ZeroAlloc.Validation;
            using ZeroAlloc.Validation.Options;
            namespace Ns;

            public sealed class SlowAttribute : AsyncValidationAttribute<string?>
            {
                public override ValueTask<bool> IsValidAsync(string? value, CancellationToken ct) => new(true);
            }

            [Validate] public class Box<T> { [Slow] public string Name { get; set; } = ""; }

            internal static class Wiring
            {
                public static void Wire(Microsoft.Extensions.DependencyInjection.IServiceCollection services) =>
                    Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions
                        .AddOptions<Box<int>>(services).ValidateWithZeroAlloc();
            }
            """,
            new ValidatorGenerator(), new OptionsValidationEmitter());

        var zv0034 = output.OnlyDiagnostic();
        Assert.Equal("ZV0034", zv0034.Id);
        Assert.Contains("'Ns.Box<int>'", zv0034.GetMessage(System.Globalization.CultureInfo.InvariantCulture), StringComparison.Ordinal);
    }
}
