using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ZeroAlloc.Validation.Generator.Shared;
using ZeroAlloc.Validation.Inject;

namespace ZeroAlloc.Validation.AspNetCore.Generator;

[Generator]
public sealed class AspNetCoreFilterEmitter : IIncrementalGenerator
{
    private const string ValidateAttributeFqn = "ZeroAlloc.Validation.ValidateAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validateClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValidateAttributeFqn,
                // RecordDeclarationSyntax covers record and record struct. Matching
                // classes only let every [Validate] record through the filter
                // unvalidated, the defect #174 fixed in Inject. The set matches
                // InjectGenerator, so both register the same validators.
                predicate: static (node, _) => node is ClassDeclarationSyntax
                                                    or RecordDeclarationSyntax,
                // A model that gets no validator is left out here too: one the generated validator
                // cannot reach, ZV0025 and #216, or a generic one, ZV0029 and #219. Naming it would
                // only add compiler errors in generated code.
                // Null marks it; Emit drops it, so the provider chain needs no extra step.
                transform: static (ctx, _) =>
                    GeneratedValidatorReach.HasGeneratedValidator((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation)
                        ? (INamedTypeSymbol)ctx.TargetSymbol
                        : null);

#pragma warning disable EPS06 // Collect() on IncrementalValuesProvider<T> is intentional
        var collected = validateClasses.Collect();
        var isInternal = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => GeneratedAccessibilityOption.IsInternal(provider));
        // The compilation lets the registration follow each validator's constructor dependencies
        // into referenced assemblies, issue #246.
        var combined = collected.Combine(isInternal).Combine(context.CompilationProvider);
#pragma warning restore EPS06
        context.RegisterSourceOutput(combined, static (ctx, pair) => EmitFiles(ctx, pair.Left.Left, pair.Left.Right, pair.Right));
    }

    private static void EmitFiles(SourceProductionContext ctx, ImmutableArray<INamedTypeSymbol?> candidates, bool isInternal, Compilation compilation)
    {
        var models = GeneratedValidatorReach.WithGeneratedValidator(candidates);
        if (models.IsDefaultOrEmpty) return;

        ctx.AddSource("ZeroAlloc.Validation.ZeroAllocValidationActionFilter.g.cs",                EmitFilter(models));
        ctx.AddSource("ZeroAlloc.Validation.ZeroAllocValidationServiceCollectionExtensions.g.cs", EmitExtensions(models, isInternal, compilation));
    }

    private static string EmitFilter(ImmutableArray<INamedTypeSymbol> models)
    {
        var sb = new StringBuilder();
        AppendFilterHeader(sb);
        AppendDispatchSwitch(sb, models);
        return sb.ToString();
    }

    private static void AppendFilterHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc.Filters;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class ZeroAllocValidationActionFilter : global::Microsoft.AspNetCore.Mvc.Filters.IAsyncActionFilter");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::System.IServiceProvider _services;");
        sb.AppendLine();
        sb.AppendLine("    public ZeroAllocValidationActionFilter(global::System.IServiceProvider services) => _services = services;");
        sb.AppendLine();
        sb.AppendLine("    public async global::System.Threading.Tasks.Task OnActionExecutionAsync(global::Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext context, global::Microsoft.AspNetCore.Mvc.Filters.ActionExecutionDelegate next)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var arg in context.ActionArguments.Values)");
        sb.AppendLine("        {");
        sb.AppendLine("            var result = await DispatchAsync(arg);");
        sb.AppendLine("            if (result is null || result.Value.IsValid) continue;");
        sb.AppendLine();
        sb.AppendLine("            var pd = new global::Microsoft.AspNetCore.Mvc.ValidationProblemDetails();");
        sb.AppendLine("            foreach (ref readonly var f in result.Value.Failures)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!pd.Errors.ContainsKey(f.PropertyName))");
        sb.AppendLine("                    pd.Errors[f.PropertyName] = global::System.Array.Empty<string>();");
        sb.AppendLine("                pd.Errors[f.PropertyName] = [.. pd.Errors[f.PropertyName], f.ErrorMessage];");
        sb.AppendLine("            }");
        sb.AppendLine("            context.Result = new global::Microsoft.AspNetCore.Mvc.UnprocessableEntityObjectResult(pd);");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine("        await next();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendDispatchSwitch(StringBuilder sb, ImmutableArray<INamedTypeSymbol> models)
    {
        sb.AppendLine("    private async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Validation.ValidationResult?> DispatchAsync(object? arg)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (arg)");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            var fullName = model.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var varName = char.ToLowerInvariant(model.Name[0]).ToString() + model.Name.Substring(1) + "_arg";
            sb.AppendLine($"            case {fullName} {varName}:");
            sb.AppendLine($"                return await _services.GetRequiredService<global::ZeroAlloc.Validation.ValidatorFor<{fullName}>>().ValidateAsync({varName});");
        }

        sb.AppendLine("            default: return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string EmitExtensions(ImmutableArray<INamedTypeSymbol> models, bool isInternal, Compilation compilation)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();
        // Documented rather than suppressed with #pragma warning disable CS1591: the
        // <auto-generated> header does not cover compiler diagnostics, and real documentation
        // also reaches the consumer's own XML documentation file.
        sb.AppendLine("/// <summary>Wires the generated validators into the ASP.NET Core MVC pipeline.</summary>");
        // ZeroAllocGeneratedAccessibility=Internal (issue #193) makes this glue internal too.
        // The method signature only ever exposes IServiceCollection, so there is no accessibility
        // conflict with the models it registers, unlike the generated validator classes.
        sb.AppendLine(isInternal
            ? "internal static class ZeroAllocValidationServiceCollectionExtensions"
            : "public static class ZeroAllocValidationServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every generated validator and adds the action filter that validates");
        sb.AppendLine("    /// incoming action arguments, returning 422 with a problem details body on failure.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to add the validation services to.</param>");
        sb.AppendLine("    /// <returns>The same service collection, so calls can be chained.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocAspNetCoreValidation(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        ValidatorRegistrationEmitter.EmitRegistrations(sb, models, compilation);

        sb.AppendLine("        services.TryAddTransient<ZeroAllocValidationActionFilter>();");
        sb.AppendLine("        services.Configure<global::Microsoft.AspNetCore.Mvc.MvcOptions>(o => o.Filters.Add<ZeroAllocValidationActionFilter>());");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
