using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ZeroAlloc.Validation.Inject;

namespace ZeroAlloc.Validation.AspNetCore.Generator;

[Generator]
public sealed class AspNetCoreFilterEmitter : IIncrementalGenerator
{
    private const string ValidateAttributeFqn = "ZeroAlloc.Validation.ValidateAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validateClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValidateAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

#pragma warning disable EPS06 // Collect() on IncrementalValuesProvider<T> is intentional
        var collected = validateClasses.Collect();
#pragma warning restore EPS06
        context.RegisterSourceOutput(collected, EmitFiles);
    }

    private static void EmitFiles(SourceProductionContext ctx, ImmutableArray<INamedTypeSymbol> models)
    {
        if (models.IsDefaultOrEmpty) return;

        ctx.AddSource("ZeroAlloc.Validation.ZeroAllocValidationActionFilter.g.cs",                EmitFilter(models));
        ctx.AddSource("ZeroAlloc.Validation.ZeroAllocValidationServiceCollectionExtensions.g.cs", EmitExtensions(models));
    }

    private static string EmitFilter(ImmutableArray<INamedTypeSymbol> models)
    {
        var sb = new StringBuilder();
        AppendFilterHeader(sb);
        AppendDispatchSwitch(sb, models);
        return sb.ToString();
    }

    private static void AppendFilterHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc.Filters;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("internal sealed class ZeroAllocValidationActionFilter : global::Microsoft.AspNetCore.Mvc.Filters.IAsyncActionFilter");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::System.IServiceProvider _services;");
        sb.AppendLine();
        sb.AppendLine("    public ZeroAllocValidationActionFilter(global::System.IServiceProvider services) => _services = services;");
        sb.AppendLine();
        sb.AppendLine("    public async global::System.Threading.Tasks.Task OnActionExecutionAsync(global::Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext context, global::Microsoft.AspNetCore.Mvc.Filters.ActionExecutionDelegate next)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var arg in context.ActionArguments.Values)");
        sb.AppendLine("        {");
        sb.AppendLine("            var result = await DispatchAsync(arg);");
        sb.AppendLine("            if (result is null || result.Value.IsValid) continue;");
        sb.AppendLine();
        sb.AppendLine("            var pd = new global::Microsoft.AspNetCore.Mvc.ValidationProblemDetails();");
        sb.AppendLine("            foreach (ref readonly var f in result.Value.Failures)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!pd.Errors.ContainsKey(f.PropertyName))");
        sb.AppendLine("                    pd.Errors[f.PropertyName] = global::System.Array.Empty<string>();");
        sb.AppendLine("                pd.Errors[f.PropertyName] = [.. pd.Errors[f.PropertyName], f.ErrorMessage];");
        sb.AppendLine("            }");
        sb.AppendLine("            context.Result = new global::Microsoft.AspNetCore.Mvc.UnprocessableEntityObjectResult(pd);");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine("        await next();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendDispatchSwitch(StringBuilder sb, ImmutableArray<INamedTypeSymbol> models)
    {
        sb.AppendLine("    private async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Validation.ValidationResult?> DispatchAsync(object? arg)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (arg)");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            var fullName = model.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var varName = char.ToLowerInvariant(model.Name[0]).ToString() + model.Name.Substring(1) + "_arg";
            sb.AppendLine($"            case {fullName} {varName}:");
            sb.AppendLine($"                return await _services.GetRequiredService<global::ZeroAlloc.Validation.ValidatorFor<{fullName}>>().ValidateAsync({varName});");
        }

        sb.AppendLine("            default: return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string EmitExtensions(ImmutableArray<INamedTypeSymbol> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();
        sb.AppendLine("public static class ZeroAllocValidationServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocAspNetCoreValidation(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        ValidatorRegistrationEmitter.EmitRegistrations(sb, models);

        sb.AppendLine("        services.TryAddTransient<ZeroAllocValidationActionFilter>();");
        sb.AppendLine("        services.Configure<global::Microsoft.AspNetCore.Mvc.MvcOptions>(o => o.Filters.Add<ZeroAllocValidationActionFilter>());");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
