using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ZeroAlloc.Validation.Generator.Shared;
using ZeroAlloc.Validation.Inject;

namespace ZeroAlloc.Validation.Options.Generator;

[Generator]
public sealed class OptionsValidationEmitter : IIncrementalGenerator
{
    private const string ValidateAttributeFqn = "ZeroAlloc.Validation.ValidateAttribute";

    /// <summary>Tracking name of the step the output is produced from, so tests can assert that it stays cached.</summary>
    internal const string OutputTrackingName = "OptionsValidationModels";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validateClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValidateAttributeFqn,
                // RecordDeclarationSyntax is a sibling of ClassDeclarationSyntax under
                // TypeDeclarationSyntax, not a subtype, so matching only the latter skipped
                // every [Validate] record. The Inject generator had the same defect, #174.
                // A record struct is also a RecordDeclarationSyntax, so it is excluded by
                // kind: OptionsBuilder<T> requires a reference type and an overload for a
                // value type would not compile.
                predicate: static (node, _) => node is ClassDeclarationSyntax
                                               || node.IsKind(SyntaxKind.RecordDeclaration),
                // A model that gets no validator is left out here too: one the generated validator
                // cannot reach, ZV0025 and #216, or a generic one, ZV0029 and #219. Naming it would
                // only add compiler errors in generated code.
                // Null marks it, and the step after Collect drops it.
                // The transform extracts everything the output needs into an equatable model, so
                // the output step stays cached while nothing it was read from changes, issue #209.
                // It reruns for every compilation, so the model still follows edits in other
                // files, such as to a nested model, and into referenced assemblies, issue #246.
                transform: static (ctx, _) =>
                    GeneratedValidatorReach.HasGeneratedValidator((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation)
                        ? ValidatedModelInfo.From((INamedTypeSymbol)ctx.TargetSymbol, ctx.SemanticModel.Compilation)
                        : null);

        var collected = validateClasses.Collect()
            .Select(static (models, _) => ValidatedModelInfo.WithGeneratedValidator(models));
        var isInternalMode = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => GeneratedAccessibilityOption.IsInternal(provider));
        var combined = collected.Combine(isInternalMode).WithTrackingName(OutputTrackingName);
        context.RegisterSourceOutput(combined, static (ctx, pair) => Emit(ctx, pair.Left, pair.Right));
    }

    private static void Emit(SourceProductionContext ctx, EquatableArray<ValidatedModelInfo> models, bool isInternalMode)
    {
        if (models.Count == 0) return;

        // An extension method cannot be more visible than the model in its signature, so
        // models that are not visible outside the assembly go in a separate internal class,
        // issue #184. Public models keep the public class exactly as before, unless
        // ZeroAllocGeneratedAccessibility=Internal (issue #193) routes every model into the
        // internal class regardless of the model's own accessibility, so the public class is
        // never emitted at all — nothing generated becomes more visible than requested.
        var publicModels   = new List<ValidatedModelInfo>();
        var internalModels = new List<ValidatedModelInfo>();
        foreach (var model in models)
            (!isInternalMode && model.IsEffectivelyPublic ? publicModels : internalModels).Add(model);

        if (publicModels.Count > 0)
        {
            ctx.AddSource(
                "ZeroAlloc.Validation.ZeroAllocOptionsValidationExtensions.g.cs",
                EmitExtensionsClass("public", "ZeroAllocOptionsValidationExtensions", publicModels));
        }

        if (internalModels.Count > 0)
        {
            ctx.AddSource(
                "ZeroAlloc.Validation.InternalZeroAllocOptionsValidationExtensions.g.cs",
                EmitExtensionsClass("internal", "InternalZeroAllocOptionsValidationExtensions", internalModels));
        }
    }

    private static string EmitExtensionsClass(string accessibility, string className, List<ValidatedModelInfo> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine();
        // Namespaced next to ZeroAllocOptionsValidator<T>, issue #193 point 2: emitting a
        // public type into the global namespace meant every library using this generator
        // shipped a same-named public type in the one namespace every consumer shares, and
        // callers relying on the old global-namespace lookup now need a using directive.
        sb.AppendLine("namespace ZeroAlloc.Validation.Options;");
        sb.AppendLine();
        // Documented rather than suppressed with #pragma warning disable CS1591: the
        // <auto-generated> header does not cover compiler diagnostics, and real documentation
        // also reaches the consumer's own XML documentation file.
        sb.AppendLine("/// <summary>Connects the generated validators to the options validation pipeline.</summary>");
        sb.AppendLine($"{accessibility} static class {className}");
        sb.AppendLine("{");

        for (var i = 0; i < models.Count; i++)
        {
            var model    = models[i];
            var modelFqn = model.FullyQualifiedName;

            // model.Name, not modelFqn: a constructed generic name would put raw angle
            // brackets in the XML and raise CS1570.
            sb.AppendLine($"    /// <summary>Validates <c>{model.Name}</c> with its generated validator whenever the options instance is resolved.</summary>");
            sb.AppendLine("    /// <param name=\"builder\">The options builder to attach validation to.</param>");
            sb.AppendLine("    /// <returns>The same options builder, so calls can be chained.</returns>");
            sb.AppendLine($"    public static global::Microsoft.Extensions.Options.OptionsBuilder<{modelFqn}> ValidateWithZeroAlloc(");
            sb.AppendLine($"        this global::Microsoft.Extensions.Options.OptionsBuilder<{modelFqn}> builder)");
            sb.AppendLine("    {");
            sb.AppendLine("        var services = builder.Services;");
            ValidatorRegistrationEmitter.AppendRegistrations(sb, [model]);
            sb.AppendLine($"        builder.Services.TryAddSingleton<global::Microsoft.Extensions.Options.IValidateOptions<{modelFqn}>,");
            sb.AppendLine($"            global::ZeroAlloc.Validation.Options.ZeroAllocOptionsValidator<{modelFqn}>>();");
            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            if (i < models.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
