using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ZeroAlloc.Validation.Inject;

namespace ZeroAlloc.Validation.Options.Generator;

[Generator]
public sealed class OptionsValidationEmitter : IIncrementalGenerator
{
    private const string ValidateAttributeFqn = "ZeroAlloc.Validation.ValidateAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validateClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValidateAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

#pragma warning disable EPS06
        var collected = validateClasses.Collect();
#pragma warning restore EPS06
        context.RegisterSourceOutput(collected, Emit);
    }

    private static void Emit(SourceProductionContext ctx, ImmutableArray<INamedTypeSymbol> models)
    {
        if (models.IsDefaultOrEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine();
        // Documented rather than suppressed with #pragma warning disable CS1591: the
        // <auto-generated> header does not cover compiler diagnostics, and real documentation
        // also reaches the consumer's own XML documentation file.
        sb.AppendLine("/// <summary>Connects the generated validators to the options validation pipeline.</summary>");
        sb.AppendLine("public static class ZeroAllocOptionsValidationExtensions");
        sb.AppendLine("{");

        for (var i = 0; i < models.Length; i++)
        {
            var model    = models[i];
            var modelFqn = model.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // model.Name, not modelFqn: a constructed generic name would put raw angle
            // brackets in the XML and raise CS1570.
            sb.AppendLine($"    /// <summary>Validates <c>{model.Name}</c> with its generated validator whenever the options instance is resolved.</summary>");
            sb.AppendLine("    /// <param name=\"builder\">The options builder to attach validation to.</param>");
            sb.AppendLine("    /// <returns>The same options builder, so calls can be chained.</returns>");
            sb.AppendLine($"    public static global::Microsoft.Extensions.Options.OptionsBuilder<{modelFqn}> ValidateWithZeroAlloc(");
            sb.AppendLine($"        this global::Microsoft.Extensions.Options.OptionsBuilder<{modelFqn}> builder)");
            sb.AppendLine("    {");
            sb.AppendLine("        var services = builder.Services;");
            ValidatorRegistrationEmitter.EmitRegistrations(sb, [model]);
            sb.AppendLine($"        builder.Services.TryAddSingleton<global::Microsoft.Extensions.Options.IValidateOptions<{modelFqn}>,");
            sb.AppendLine($"            global::ZeroAlloc.Validation.Options.ZeroAllocOptionsValidator<{modelFqn}>>();");
            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            if (i < models.Length - 1)
                sb.AppendLine();
        }

        sb.AppendLine("}");

        ctx.AddSource("ZeroAlloc.Validation.ZeroAllocOptionsValidationExtensions.g.cs", sb.ToString());
    }
}
