using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZValidation.Generator;

[Generator]
public sealed class ValidatorGenerator : IIncrementalGenerator
{
    private const string ValidateAttributeFqn = "ZValidation.ValidateAttribute";
    private const string TransientFqn = "ZeroAlloc.Inject.TransientAttribute";
    private const string ScopedFqn    = "ZeroAlloc.Inject.ScopedAttribute";
    private const string SingletonFqn = "ZeroAlloc.Inject.SingletonAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validateClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValidateAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(validateClasses, Emit);
    }

    private static void Emit(SourceProductionContext ctx, INamedTypeSymbol classSymbol)
    {
        if (classSymbol.DeclaredAccessibility == Accessibility.Private)
            return;

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var validatorName = $"{classSymbol.Name}Validator";
        var modelName = classSymbol.Name;

        var sb = new System.Text.StringBuilder();
        EmitFileHeader(sb, namespaceName, classSymbol, validatorName, modelName);

        var nestedFields = RuleEmitter.CollectNestedValidatorFields(classSymbol);
        EmitFieldsAndConstructor(sb, validatorName, nestedFields);

        sb.AppendLine($"    public override global::ZValidation.ValidationResult Validate({modelName} instance)");
        sb.AppendLine("    {");
        RuleEmitter.EmitValidateBody(sb, classSymbol);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{validatorName}.g.cs", sb.ToString());
    }

    private static void EmitFileHeader(
        System.Text.StringBuilder sb,
        string? namespaceName,
        INamedTypeSymbol classSymbol,
        string validatorName,
        string modelName)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable HLQ004 // ref readonly foreach on ReadOnlySpan<struct>");
        sb.AppendLine("#pragma warning disable HLQ012 // CollectionsMarshal.AsSpan not needed in generated code");
        sb.AppendLine("#pragma warning disable EPS06  // False positive: ValidationFailure is a readonly struct");
        sb.AppendLine();
        sb.AppendLine("using ZValidation;");
        sb.AppendLine();

        if (namespaceName is not null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        var lifetimeFqn = classSymbol.GetAttributes()
            .Select(a => a.AttributeClass?.ToDisplayString())
            .FirstOrDefault(fqn => fqn is TransientFqn or ScopedFqn or SingletonFqn);

        if (lifetimeFqn is not null)
            sb.AppendLine($"[global::{lifetimeFqn}]");

        sb.AppendLine($"public sealed partial class {validatorName} : ValidatorFor<{modelName}>");
        sb.AppendLine("{");
    }

    private static void EmitFieldsAndConstructor(
        System.Text.StringBuilder sb,
        string validatorName,
        List<(string FieldName, string ParamName, string QualifiedValidatorType)> nestedFields)
    {
        if (nestedFields.Count == 0)
            return;

        foreach (var (fieldName, _, qualifiedType) in nestedFields)
            sb.AppendLine($"    private readonly {qualifiedType} {fieldName};");

        sb.AppendLine();

        sb.Append($"    public {validatorName}(");
        for (int fi = 0; fi < nestedFields.Count; fi++)
        {
            var (_, paramName, qualifiedType) = nestedFields[fi];
            if (fi > 0) sb.Append(", ");
            sb.Append($"{qualifiedType} {paramName}");
        }
        sb.AppendLine(")");
        sb.AppendLine("    {");
        foreach (var (fieldName, paramName, _) in nestedFields)
            sb.AppendLine($"        {fieldName} = {paramName};");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
