using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZValidation.Generator;

[Generator]
public sealed class ValidatorGenerator : IIncrementalGenerator
{
    private const string ValidateAttributeFqn = "ZValidation.ValidateAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var validateClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ValidateAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Where(static s => s is not null);

        context.RegisterSourceOutput(validateClasses, Emit);
    }

    private static void Emit(SourceProductionContext ctx, INamedTypeSymbol classSymbol)
    {
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var validatorName = $"{classSymbol.Name}Validator";
        var modelName = classSymbol.Name;

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using ZValidation;");
        sb.AppendLine();

        if (namespaceName is not null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"public sealed partial class {validatorName} : ValidatorFor<{modelName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public override global::ZValidation.ValidationResult Validate({modelName} instance)");
        sb.AppendLine("    {");

        RuleEmitter.EmitValidateBody(sb, classSymbol);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{validatorName}.g.cs", sb.ToString());
    }
}
