using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace ZeroAlloc.Validation.Generator;

/// <summary>
/// The code the generated validator uses to call the model's methods, and the file context it
/// is compiled in. The emitter and <see cref="MethodCallProbe"/> both build their text here, so
/// the probe compiles exactly what the validator will contain.
/// </summary>
internal static class GeneratedCalls
{
    /// <summary>
    /// The start of every generated validator file: <see cref="AppendHeader"/>, then the model's
    /// namespace as a file-scoped declaration.
    /// </summary>
    public static void AppendPreamble(StringBuilder sb, string? namespaceName)
    {
        AppendHeader(sb);
        if (namespaceName is not null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// The header and <c>using</c> directives every generated validator file starts with. The
    /// <c>using</c> directives decide which extension methods a call such as
    /// <c>instance.Name()</c> can bind to. <see cref="MethodCallProbe"/> follows them with block
    /// namespaces, one per model namespace, which bind exactly as the file-scoped one does: a
    /// file-scoped namespace is defined as a block namespace around the rest of the file.
    /// </summary>
    public static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using ZeroAlloc.Validation;");
        sb.AppendLine();
    }

    /// <summary>The namespace the validator for <paramref name="model"/> is declared in.</summary>
    public static string? NamespaceOf(INamedTypeSymbol model) =>
        model.ContainingNamespace.IsGlobalNamespace ? null : model.ContainingNamespace.ToDisplayString();

    /// <summary>The value a <c>[Must]</c> predicate receives: the property, not unwrapped.</summary>
    public static string RawPropertyAccess(string model, IPropertySymbol prop) => $"{model}.{prop.Name}";

    /// <summary>A <c>When</c> guard, followed by the rule's condition.</summary>
    public static string WhenGuard(string model, string method) => $"{model}.{method}() && ";

    /// <summary>An <c>Unless</c> guard, followed by the rule's condition.</summary>
    public static string UnlessGuard(string model, string method) => $"!{model}.{method}() && ";

    /// <summary>A <c>[Must]</c> rule's failure condition.</summary>
    public static string MustCondition(string model, string method, string argument) => $"!{model}.{method}({argument})";

    /// <summary>The <c>[SkipWhen]</c> condition.</summary>
    public static string SkipWhenCondition(string model, string method) => $"{model}.{method}()";

    /// <summary>A <c>[CustomValidation]</c> call, on the model or through <paramref name="receiverType"/>.</summary>
    public static string CustomValidationCall(string model, string method, string? receiverType) =>
        receiverType is null ? $"{model}.{method}()" : $"(({receiverType}){model}).{method}()";

    /// <summary>
    /// Whether <paramref name="name"/> can follow <c>instance.</c> in generated code at all. Any
    /// other text would not parse there, so it is reported without being compiled.
    /// </summary>
    public static bool IsMethodName(string name) =>
        SyntaxFacts.IsValidIdentifier(name) && SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None;
}
