using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using ZeroAlloc.Validation.Generator.Shared;

namespace ZeroAlloc.Validation.Generator;

/// <summary>
/// The code the generated validator uses to read the model's properties and call its methods,
/// and the file context it is compiled in. The emitter and <see cref="MethodCallProbe"/> both
/// build their text here, so the probe compiles exactly what the validator will contain. Every
/// member name goes through <see cref="Identifier"/>, so one declared with a keyword name, such
/// as <c>@class</c>, is written <c>instance.@class</c>, issue #242.
/// </summary>
internal static class GeneratedCalls
{
    /// <summary>
    /// The start of every generated validator file: <see cref="AppendHeader"/>, then the model's
    /// namespace as a file-scoped declaration.
    /// </summary>
    public static void AppendPreamble(StringBuilder sb, string? namespaceName)
    {
        AppendHeader(sb);
        if (namespaceName is not null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// The header and <c>using</c> directives every generated validator file starts with. The
    /// <c>using</c> directives decide which extension methods a call such as
    /// <c>instance.Name()</c> can bind to. <see cref="MethodCallProbe"/> follows them with block
    /// namespaces, one per model namespace, which bind exactly as the file-scoped one does: a
    /// file-scoped namespace is defined as a block namespace around the rest of the file.
    /// </summary>
    public static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using ZeroAlloc.Validation;");
        sb.AppendLine();
    }

    /// <summary>The namespace the validator for <paramref name="model"/> is declared in.</summary>
    public static string? NamespaceOf(INamedTypeSymbol model) => GeneratedValidatorNames.NamespaceName(model);

    /// <summary>
    /// <paramref name="name"/>, a member name as the symbol reports it, written as C# code: a
    /// reserved keyword such as <c>class</c> gets the <c>@</c> escape it was declared with. A
    /// contextual keyword such as <c>value</c> or <c>nameof</c> is an identifier wherever the
    /// generated code names a member, after <c>instance.</c>, so it is left as it is.
    /// </summary>
    public static string Identifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;

    /// <summary><c>instance.Member</c>, with the member name escaped where it is a keyword.</summary>
    public static string MemberAccess(string model, string member) => $"{model}.{Identifier(member)}";

    /// <summary>The value a <c>[Must]</c> predicate receives: the property, not unwrapped.</summary>
    public static string RawPropertyAccess(string model, IPropertySymbol prop) => MemberAccess(model, prop.Name);

    /// <summary>
    /// <c>instance.Method(argument)</c>, or <c>instance.Method()</c> when
    /// <paramref name="argument"/> is empty: the call itself, which is what
    /// <see cref="CallSite.Text"/> records and a mirrored warning is located in.
    /// </summary>
    public static string MethodCall(string model, string method, string argument = "") => $"{MemberAccess(model, method)}({argument})";

    /// <summary>A <c>When</c> guard, followed by the rule's condition.</summary>
    public static string WhenGuard(string model, string method) => $"{MethodCall(model, method)} && ";

    /// <summary>An <c>Unless</c> guard, followed by the rule's condition.</summary>
    public static string UnlessGuard(string model, string method) => $"!{MethodCall(model, method)} && ";

    /// <summary>A <c>[Must]</c> rule's failure condition.</summary>
    public static string MustCondition(string model, string method, string argument) => $"!{MethodCall(model, method, argument)}";

    /// <summary>The <c>[SkipWhen]</c> condition.</summary>
    public static string SkipWhenCondition(string model, string method) => MethodCall(model, method);

    /// <summary>A <c>[CustomValidation]</c> call, on the model or through <paramref name="receiverType"/>.</summary>
    public static string CustomValidationCall(string model, string method, string? receiverType) =>
        receiverType is null ? MethodCall(model, method) : MethodCall($"(({receiverType}){model})", method);

    /// <summary>A custom rule's call, on the static field holding the rule instance.</summary>
    public static string RuleCall(string field, string argument) => $"{field}.IsValid({argument})";

    /// <summary>
    /// Whether <paramref name="name"/> can follow <c>instance.</c> in generated code at all, once
    /// <see cref="Identifier"/> has escaped it. Any other text would not parse there, so it is
    /// reported without being compiled.
    /// </summary>
    public static bool IsMethodName(string name) => SyntaxFacts.IsValidIdentifier(name);
}
