using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ZeroAlloc.Validation.Generator.Shared;

namespace ZeroAlloc.Validation.Generator;

/// <summary>
/// ZV0034: options validation is synchronous. <c>IValidateOptions&lt;T&gt;</c> has no
/// asynchronous form, so the <c>ValidateWithZeroAlloc()</c> extension the Options package
/// generates calls the model's synchronous <c>Validate</c>, which throws for a model with
/// asynchronous rules. Each call of it on an <c>OptionsBuilder&lt;T&gt;</c> of such a model is
/// reported at the call, so the build fails there instead of the application at startup.
/// </summary>
/// <remarks>
/// The extension is generated by another generator, so it does not exist in the compilation this
/// generator sees, and the call cannot be bound. It is recognised by name, and the model by the
/// type of the builder it is called on: <c>builder.ValidateWithZeroAlloc()</c>,
/// <c>builder?.ValidateWithZeroAlloc()</c>, or the static form, whose first argument is the
/// builder. The synchronous <c>Validate</c> still throws for any other route, such as registering
/// <c>ZeroAllocOptionsValidator&lt;T&gt;</c> by hand.
/// </remarks>
internal static class SyncOnlyOptionsValidation
{
    /// <summary>Tracking name of the ZV0034 step, so tests can assert that it stays cached.</summary>
    internal const string TrackingName = "SyncOnlyOptionsValidation";

    private const string MethodName = "ValidateWithZeroAlloc";
    private const string OptionsBuilderMetadataName = "OptionsBuilder`1";
    private const string OptionsNamespace = "Microsoft.Extensions.Options";
    private const string ValidateAttributeFqn = "ZeroAlloc.Validation.ValidateAttribute";

    public static readonly DiagnosticDescriptor ZV0034 = new(
        id: "ZV0034",
        title: "Options validation of a model with asynchronous rules",
        messageFormat: "'{0}' has asynchronous validation rules, which options validation cannot run because it is synchronous; "
            + "validate the options with ValidateAsync where they are used, or move the asynchronous rules off the options model",
        category: "ZeroAlloc.Validation",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description:
            "IValidateOptions<T> is synchronous, so ValidateWithZeroAlloc() validates the options with the "
            + "generated validator's Validate. For a model with an AsyncValidationAttribute<T> rule, directly "
            + "or through a nested or collection property, Validate cannot run that rule and throws "
            + "NotSupportedException rather than skip it, which would fail the application when the options "
            + "are first resolved. The call is reported instead.");

    /// <summary>A <c>ValidateWithZeroAlloc</c> call as the syntax provider finds it, comparing by value, issue #209.</summary>
    private sealed record CallTarget(SyntaxTree Tree, Microsoft.CodeAnalysis.Text.TextSpan Span);

    /// <summary>A call of it on a model with asynchronous rules: the model's name and where to report it.</summary>
    private sealed record Finding(string ModelName, LocationInfo Location);

    public static void Register(IncrementalGeneratorInitializationContext context)
    {
        var calls = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is InvocationExpressionSyntax invocation && IsCandidate(invocation),
            transform: static (ctx, _) => new CallTarget(ctx.Node.SyntaxTree, ctx.Node.Span));

        // Whether the model has asynchronous rules depends on the whole compilation, not only on
        // the file holding the call, so it is decided against each compilation, as the validators
        // are, and the output step is cached while the finding stays the same.
        var findings = calls
            .Combine(context.CompilationProvider)
            .Select(static (input, ct) => Find(input.Left, input.Right, ct))
            .Where(static finding => finding is not null)
            .WithTrackingName(TrackingName);

        context.RegisterSourceOutput(findings, static (ctx, finding) =>
            ctx.ReportDiagnostic(Diagnostic.Create(ZV0034, finding!.Location.ToLocation(), finding.ModelName)));
    }

    private static bool IsCandidate(InvocationExpressionSyntax invocation) => invocation.Expression switch
    {
        MemberAccessExpressionSyntax access => IsMethodName(access.Name),
        MemberBindingExpressionSyntax binding => IsMethodName(binding.Name),
        IdentifierNameSyntax name => IsMethodName(name),
        _ => false,
    };

    private static bool IsMethodName(SimpleNameSyntax name) =>
        string.Equals(name.Identifier.ValueText, MethodName, System.StringComparison.Ordinal);

    private static Finding? Find(CallTarget target, Compilation compilation, System.Threading.CancellationToken ct)
    {
        if (target.Tree.GetRoot(ct).FindNode(target.Span, getInnermostNodeForTie: true) is not InvocationExpressionSyntax invocation)
            return null;

        var semanticModel = compilation.GetSemanticModel(target.Tree);
        if (FindOptionsModel(invocation, semanticModel, ct) is not { } model)
            return null;

        if (!HasValidateAttribute(model)
            || !GeneratedValidatorReach.HasGeneratedValidator(model, compilation)
            || !RuleEmitter.RequiresAsync(model, compilation))
            return null;

        return new Finding(model.ToDisplayString(), new LocationInfo(target.Tree, invocation.Span));
    }

    /// <summary>
    /// The options model of the builder the extension is called on: the receiver of
    /// <c>builder.Method()</c> or <c>builder?.Method()</c>, or else the first argument, as in the
    /// static form <c>Extensions.Method(builder)</c>. The generated extensions class is not in the
    /// compilation either, so its name binds to nothing and cannot tell the forms apart.
    /// </summary>
    private static INamedTypeSymbol? FindOptionsModel(InvocationExpressionSyntax invocation, SemanticModel semanticModel, System.Threading.CancellationToken ct)
    {
        ExpressionSyntax? receiver = invocation.Expression switch
        {
            MemberAccessExpressionSyntax access => access.Expression,
            MemberBindingExpressionSyntax => FindConditionalReceiver(invocation),
            _ => null,
        };

        if (receiver is not null && OptionsModel(semanticModel.GetTypeInfo(receiver, ct).Type) is { } model)
            return model;

        return invocation.ArgumentList.Arguments.Count > 0
            ? OptionsModel(semanticModel.GetTypeInfo(invocation.ArgumentList.Arguments[0].Expression, ct).Type)
            : null;
    }

    private static ExpressionSyntax? FindConditionalReceiver(SyntaxNode node)
    {
        for (var current = node.Parent; current is not null; current = current.Parent)
        {
            if (current is ConditionalAccessExpressionSyntax conditional && conditional.WhenNotNull.Span.Contains(node.Span))
                return conditional.Expression;
        }
        return null;
    }

    private static INamedTypeSymbol? OptionsModel(ITypeSymbol? type) =>
        type is INamedTypeSymbol { IsGenericType: true } named
        && string.Equals(named.OriginalDefinition.MetadataName, OptionsBuilderMetadataName, System.StringComparison.Ordinal)
        && string.Equals(named.ContainingNamespace?.ToDisplayString(), OptionsNamespace, System.StringComparison.Ordinal)
        && named.TypeArguments[0] is INamedTypeSymbol model
            ? model
            : null;

    private static bool HasValidateAttribute(INamedTypeSymbol type)
    {
        foreach (var attr in type.GetAttributes())
        {
            if (string.Equals(attr.AttributeClass?.ToDisplayString(), ValidateAttributeFqn, System.StringComparison.Ordinal))
                return true;
        }
        return false;
    }
}
